In [1]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName('Demo').getOrCreate()

In [2]:
spark

In [3]:
import pandas as pd

In [4]:
file = pd.read_csv('movie.csv')
file.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [5]:
movie = spark.read.csv('movie.csv', header=True, inferSchema=True)
movie.show(15)

+-----+-----------------+----------------------+--------+-----------------------+----------------------+-----------------+----------------------+------------+--------------------+------------------+--------------------+---------------+-------------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------+-------+--------------+-------+----------+----------------------+----------+------------+--------------------+
|color|    director_name|num_critic_for_reviews|duration|director_facebook_likes|actor_3_facebook_likes|     actor_2_name|actor_1_facebook_likes|       gross|              genres|      actor_1_name|         movie_title|num_voted_users|cast_total_facebook_likes|        actor_3_name|facenumber_in_poster|       plot_keywords|     movie_imdb_link|num_user_for_reviews|language|country|content_rating| budget|title_year|actor_2_facebook_likes|imdb_score|aspect_ratio|movie_facebook_likes|
+-----+-----------------+----------------------+--------+-----------------------+----------------------+-----------------+----------------------+------------+--------------------+------------------+--------------------+---------------+-------------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------+-------+--------------+-------+----------+----------------------+----------+------------+--------------------+
|Color|    James Cameron|                 723.0|   178.0|                    0.0|                 855.0| Joel David Moore|                1000.0|7.60505847E8|Action|Adventure|...|       CCH Pounder|              Avatar|         886204|                     4834|           Wes Studi|                 0.0|avatar|future|mar...|http://www.imdb.c...|              3054.0| English|    USA|         PG-13| 2.37E8|    2009.0|                 936.0|       7.9|        1.78|               33000|
|Color|   Gore Verbinski|                 302.0|   169.0|                  563.0|                1000.0|    Orlando Bloom|               40000.0|3.09404152E8|Action|Adventure|...|       Johnny Depp|Pirates of the Ca...|         471220|                    48350|      Jack Davenport|                 0.0|goddess|marriage ...|http://www.imdb.c...|              1238.0| English|    USA|         PG-13|  3.0E8|    2007.0|                5000.0|       7.1|        2.35|                   0|
|Color|       Sam Mendes|                 602.0|   148.0|                    0.0|                 161.0|     Rory Kinnear|               11000.0|2.00074175E8|Action|Adventure|...|   Christoph Waltz|             Spectre|         275868|                    11700|    Stephanie Sigman|                 1.0|bomb|espionage|se...|http://www.imdb.c...|               994.0| English|     UK|         PG-13| 2.45E8|    2015.0|                 393.0|       6.8|        2.35|               85000|
|Color|Christopher Nolan|                 813.0|   164.0|                22000.0|               23000.0|   Christian Bale|               27000.0|4.48130642E8|     Action|Thriller|         Tom Hardy|The Dark Knight R...|        1144337|                   106759|Joseph Gordon-Levitt|                 0.0|deception|impriso...|http://www.imdb.c...|              2701.0| English|    USA|         PG-13|  2.5E8|    2012.0|               23000.0|       8.5|        2.35|              164000|
| NULL|      Doug Walker|                  NULL|    NULL|                  131.0|                  NULL|       Rob Walker|                 131.0|        NULL|         Documentary|       Doug Walker|Star Wars: Episod...|              8|                      143|                NULL|                 0.0|                NULL|http://www.imdb.c...|                NULL|    NULL|   NULL|          NULL|   NULL|      NULL|                  12.0|       7.1|        NULL|                   0|
|Color|   Andrew Stanton|                 462.0|   132.0|                  475.0|                 530.0|  Samantha Morton|                 640.0| 7.3058679E7|Action|Adventure|...|      Daryl Sabara|         John Carter|         212204|                     1873|        Polly Walker|                 1.0|alien|american ci...|http://www.imdb.c...|               738.0| English|    USA|         PG-13|2.637E8|    2012.0|                 632.0|       6.6|        2.35|               24000|
|Color|        Sam Raimi|                 392.0|   156.0|                    0.0|                4000.0|     James Franco|               24000.0|3.36530303E8|Action|Adventure|...|      J.K. Simmons|        Spider-Man 3|         383056|                    46055|       Kirsten Dunst|                 0.0|sandman|spider ma...|http://www.imdb.c...|              1902.0| English|    USA|         PG-13| 2.58E8|    2007.0|               11000.0|       6.2|        2.35|                   0|
|Color|     Nathan Greno|                 324.0|   100.0|                   15.0|                 284.0|     Donna Murphy|                 799.0|2.00807262E8|Adventure|Animati...|      Brad Garrett|             Tangled|         294810|                     2036|         M.C. Gainey|                 1.0|17th century|base...|http://www.imdb.c...|               387.0| English|    USA|            PG|  2.6E8|    2010.0|                 553.0|       7.8|        1.85|               29000|
|Color|      Joss Whedon|                 635.0|   141.0|                    0.0|               19000.0|Robert Downey Jr.|               26000.0|4.58991599E8|Action|Adventure|...|   Chris Hemsworth|Avengers: Age of ...|         462669|                    92000|  Scarlett Johansson|                 4.0|artificial intell...|http://www.imdb.c...|              1117.0| English|    USA|         PG-13|  2.5E8|    2015.0|               21000.0|       7.5|        2.35|              118000|
|Color|      David Yates|                 375.0|   153.0|                  282.0|               10000.0| Daniel Radcliffe|               25000.0| 3.0195698E8|Adventure|Family|...|      Alan Rickman|Harry Potter and ...|         321795|                    58753|        Rupert Grint|                 3.0|blood|book|love|p...|http://www.imdb.c...|               973.0| English|     UK|            PG|  2.5E8|    2009.0|               11000.0|       7.5|        2.35|               10000|
|Color|      Zack Snyder|                 673.0|   183.0|                    0.0|                2000.0|     Lauren Cohan|               15000.0|3.30249062E8|Action|Adventure|...|      Henry Cavill|Batman v Superman...|         371639|                    24450|      Alan D. Purwin|                 0.0|based on comic bo...|http://www.imdb.c...|              3018.0| English|    USA|         PG-13|  2.5E8|    2016.0|                4000.0|       6.9|        2.35|              197000|
|Color|     Bryan Singer|                 434.0|   169.0|                    0.0|                 903.0|    Marlon Brando|               18000.0|2.00069408E8|Action|Adventure|...|      Kevin Spacey|    Superman Returns|         240396|                    29991|      Frank Langella|                 0.0|crystal|epic|lex ...|http://www.imdb.c...|              2367.0| English|    USA|         PG-13| 2.09E8|    2006.0|               10000.0|       6.1|        2.35|                   0|
|Color|     Marc Forster|                 403.0|   106.0|                  395.0|                 393.0|  Mathieu Amalric|                 451.0|1.68368427E8|    Action|Adventure|Giancarlo Giannini|   Quantum of Solace|         330784|                     2023|        Rory Kinnear|                 1.0|action hero|attem...|http://www.imdb.c...|              1243.0| English|     UK|         PG-13|  2.0E8|    2008.0|                 412.0|       6.7|        2.35|                   0|
|Color|   Gore Verbinski|                 313.0|   151.0|                  563.0|                1000.0|    Orlando Bloom|               40000.0|4.23032628E8|Action|Adventure|...|       Johnny Depp|Pirates of the Ca...|         522040|                    48486|      Jack Davenport|                 2.0|box office hit|gi...|http://www.imdb.c...|              1832.0| English|    USA|         PG-13| 2.25E8|    2006.0|                5000.0|       7.3|        2.35|                5000|
|Color|   Gore Verbinski|                 450.0|   150.0|                  563.0|                1000.0|      Ruth Wilson|               40000.0|  8.928991E7|Action|Adventure|...|       Johnny Depp|     The Lone Ranger|         181792|                    45757|       Tom Wilkinson|                 1.0|horse|outlaw|texa...|http://www.imdb.c...|               711.0| English|    USA|         PG-13| 2.15E8|    2013.0|                2000.0|       6.5|        2.35|               48000|
+-----+-----------------+----------------------+--------+-----------------------+----------------------+-----------------+----------------------+------------+--------------------+------------------+--------------------+---------------+-------------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------+-------+--------------+-------+----------+----------------------+----------+------------+--------------------+
only showing top 15 rows

In [7]:
movie.printSchema()

root
 |-- color: string (nullable = true)
 |-- director_name: string (nullable = true)
 |-- num_critic_for_reviews: double (nullable = true)
 |-- duration: double (nullable = true)
 |-- director_facebook_likes: double (nullable = true)
 |-- actor_3_facebook_likes: double (nullable = true)
 |-- actor_2_name: string (nullable = true)
 |-- actor_1_facebook_likes: double (nullable = true)
 |-- gross: double (nullable = true)
 |-- genres: string (nullable = true)
 |-- actor_1_name: string (nullable = true)
 |-- movie_title: string (nullable = true)
 |-- num_voted_users: integer (nullable = true)
 |-- cast_total_facebook_likes: integer (nullable = true)
 |-- actor_3_name: string (nullable = true)
 |-- facenumber_in_poster: double (nullable = true)
 |-- plot_keywords: string (nullable = true)
 |-- movie_imdb_link: string (nullable = true)
 |-- num_user_for_reviews: double (nullable = true)
 |-- language: string (nullable = true)
 |-- country: string (nullable = true)
 |-- content_rating: string (nullable = true)
 |-- budget: double (nullable = true)
 |-- title_year: double (nullable = true)
 |-- actor_2_facebook_likes: double (nullable = true)
 |-- imdb_score: double (nullable = true)
 |-- aspect_ratio: double (nullable = true)
 |-- movie_facebook_likes: integer (nullable = true)

In [8]:
file[['color', 'director_name']]

      color      director_name
0     Color      James Cameron
1     Color     Gore Verbinski
2     Color         Sam Mendes
3     Color  Christopher Nolan
4       NaN        Doug Walker
...     ...                ...
4911  Color        Scott Smith
4912  Color                NaN
4913  Color   Benjamin Roberds
4914  Color        Daniel Hsia
4915  Color           Jon Gunn

[4916 rows x 2 columns]

In [13]:
movie.select(movie.color, movie.country).show(11)

+-----+-------+
|color|country|
+-----+-------+
|Color|    USA|
|Color|    USA|
|Color|     UK|
|Color|    USA|
| NULL|   NULL|
|Color|    USA|
|Color|    USA|
|Color|    USA|
|Color|    USA|
|Color|     UK|
|Color|    USA|
+-----+-------+
only showing top 11 rows